### ISSUE TITLE
crash when warping to hub

### ISSUE THREAD

**Issue by Link-Satonaka** [Kaldaien/SoulsUnsqueezed#1]
I've only just started the game so there may be more scenarios that cause it to crash, but my game crashes every time I leave multiplayer as a phantom, and every time I try to warp to the main hub.

crash log: http://sprunge.us/bAKd

**Comment by Kaldaien** [comment]
This is a UI problem, not related to anything I've done unfortunately. You discovered a bug that FromSoftware needs to fix :-\
